// Code generated by MockGen. DO NOT EDIT.
// Source: people.go

// Package mock_model is a generated GoMock package.
package mock_model

import (
	gomock "github.com/golang/mock/gomock"
	entity "github.com/sh-tatsuno/shabm/entity"
	reflect "reflect"
)

// MockPersonModelInterface is a mock of PersonModelInterface interface
type MockPersonModelInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPersonModelInterfaceMockRecorder
}

// MockPersonModelInterfaceMockRecorder is the mock recorder for MockPersonModelInterface
type MockPersonModelInterfaceMockRecorder struct {
	mock *MockPersonModelInterface
}

// NewMockPersonModelInterface creates a new mock instance
func NewMockPersonModelInterface(ctrl *gomock.Controller) *MockPersonModelInterface {
	mock := &MockPersonModelInterface{ctrl: ctrl}
	mock.recorder = &MockPersonModelInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPersonModelInterface) EXPECT() *MockPersonModelInterfaceMockRecorder {
	return m.recorder
}

// GetAllPeople mocks base method
func (m *MockPersonModelInterface) GetAllPeople() ([]entity.Person, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPeople")
	ret0, _ := ret[0].([]entity.Person)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPeople indicates an expected call of GetAllPeople
func (mr *MockPersonModelInterfaceMockRecorder) GetAllPeople() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPeople", reflect.TypeOf((*MockPersonModelInterface)(nil).GetAllPeople))
}

// CreatePerson mocks base method
func (m *MockPersonModelInterface) CreatePerson(person entity.Person) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePerson", person)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePerson indicates an expected call of CreatePerson
func (mr *MockPersonModelInterfaceMockRecorder) CreatePerson(person interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePerson", reflect.TypeOf((*MockPersonModelInterface)(nil).CreatePerson), person)
}
