// Code generated by MockGen. DO NOT EDIT.
// Source: people.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	gomock "github.com/golang/mock/gomock"
	entity "github.com/sh-tatsuno/shabm/entity"
	reflect "reflect"
)

// MockPersonServiceInterface is a mock of PersonServiceInterface interface
type MockPersonServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPersonServiceInterfaceMockRecorder
}

// MockPersonServiceInterfaceMockRecorder is the mock recorder for MockPersonServiceInterface
type MockPersonServiceInterfaceMockRecorder struct {
	mock *MockPersonServiceInterface
}

// NewMockPersonServiceInterface creates a new mock instance
func NewMockPersonServiceInterface(ctrl *gomock.Controller) *MockPersonServiceInterface {
	mock := &MockPersonServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPersonServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPersonServiceInterface) EXPECT() *MockPersonServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAllPeople mocks base method
func (m *MockPersonServiceInterface) GetAllPeople() ([]entity.Person, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPeople")
	ret0, _ := ret[0].([]entity.Person)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPeople indicates an expected call of GetAllPeople
func (mr *MockPersonServiceInterfaceMockRecorder) GetAllPeople() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPeople", reflect.TypeOf((*MockPersonServiceInterface)(nil).GetAllPeople))
}

// CreatePerson mocks base method
func (m *MockPersonServiceInterface) CreatePerson(person entity.Person) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePerson", person)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePerson indicates an expected call of CreatePerson
func (mr *MockPersonServiceInterfaceMockRecorder) CreatePerson(person interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePerson", reflect.TypeOf((*MockPersonServiceInterface)(nil).CreatePerson), person)
}
